language: elixir
elixir:
  - 1.4.0
otp_release:
  - 18.2
  - 19.1
addons:
  postgresql: "9.5"
sudo: required
dist: trusty
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
notifications:
  recipients:
    - kelostrada@gmail.com
