language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.1
matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0
      otp_release: 18.2
    - elixir: 1.3.2
      otp_release: 19.1
before_install:
  - sudo service postgresql stop
  - sudo apt-get -y -qq --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-contrib-$PGVERSION
sudo: required
dist: trusty
cache: apt
env:
  global:
    - PGVERSION=9.6
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
notifications:
  recipients:
    - kelostrada@gmail.com
